objs=[
  {"id"=>1, "title"=>"background-attachment", "pvalues"=>"scroll,fixed", "pvalues_desc"=>"Scroll,Fixed", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"background-attachment"},
  {"id"=>2, "title"=>"background-color", "pvalues"=>"transparent,aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "pvalues_desc"=>"transparent,aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"background-color"},
  {"id"=>3, "title"=>"background-image", "pvalues"=>"none,0i", "pvalues_desc"=>"None,0i", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"background-image"},
  {"id"=>4, "title"=>"background-position", "pvalues"=>"left|top,center|center,right|bottom,l1|l1", "pvalues_desc"=>"Left|top,Center|center,Right|bottom,L1|l1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"hv", "css_name"=>"background-position"},
  {"id"=>5, "title"=>"background-repeat", "pvalues"=>"repeat,repeat-x,repeat-y,no-repeat", "pvalues_desc"=>"Repeat,Repeat-x,Repeat-y,No-repeat", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"background-repeat"},
  {"id"=>6, "title"=>"border-color", "pvalues"=>"transparent,aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "pvalues_desc"=>"Transparent,Aqua,Black,Blue,Fuchsia,Gray,Green,Lime,Maroon,Navy,Olive,Purple,Red,Silver,Teal,White,Yellow,0c", "punits"=>"hex,rgb", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"trbl", "css_name"=>"border-color"},
  {"id"=>7, "title"=>"border-style", "pvalues"=>"none,double,solid,dashed,dotted,ridge,outset,groove,inset", "pvalues_desc"=>"None,Double,Solid,Dashed,Dotted,Ridge,Outset,Groove,Inset", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"trbl", "css_name"=>"border-style"},
  {"id"=>8, "title"=>"border-width", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"trbl", "css_name"=>"border-width"},
  {"id"=>9, "title"=>"clear", "pvalues"=>"none,left,right,both", "pvalues_desc"=>"None,Left,Right,Both", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"clear"},
  {"id"=>10, "title"=>"cursor", "pvalues"=>"auto,default,crosshair,pointer,move,n-resize,ne-resize,e-resize,se-resize,s-resize,sw-resize,w-resize,nw-resize,text,wait,help", "pvalues_desc"=>"Auto,Default,Crosshair,Pointer,Move,N-resize,Ne-resize,E-resize,Se-resize,S-resize,Sw-resize,W-resize,Nw-resize,Text,Wait,Help", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"cursor"},
  {"id"=>11, "title"=>"display", "pvalues"=>"inline,none,block,list-item,run-in,compact,marker,table,inline-table,table-row-group,table-header-group,table-footer-group,table-row,table-column-group,table-column,table-cell,table-caption", "pvalues_desc"=>"Inline,None,Block,List-item,Run-in,Compact,Marker,Table,Inline-table,Table-row-group,Table-header-group,Table-footer-group,Table-row,Table-column-group,Table-column,Table-cell,Table-caption", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"display"},
  {"id"=>12, "title"=>"float", "pvalues"=>"none,left,right", "pvalues_desc"=>"None,Left,Right", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"float"},
  {"id"=>13, "title"=>"position", "pvalues"=>"static,relative,absolute,fixed", "pvalues_desc"=>"Static,Relative,Absolute,Fixed", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"position"},
  {"id"=>14, "title"=>"visibility", "pvalues"=>"visible,hidden,collapse", "pvalues_desc"=>"Visible,Hidden,Collapse", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"visibility"},
  {"id"=>15, "title"=>"height", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"height"},
  {"id"=>16, "title"=>"line-height", "pvalues"=>"normal,l1", "pvalues_desc"=>"Normal,L1", "punits"=>"l,%,f", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"line-height"},
  {"id"=>17, "title"=>"max-height", "pvalues"=>"none,l1", "pvalues_desc"=>"None,L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"max-height"},
  {"id"=>18, "title"=>"max-width", "pvalues"=>"none,l1", "pvalues_desc"=>"None,L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"max-width"},
  {"id"=>19, "title"=>"min-height", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"min-height"},
  {"id"=>20, "title"=>"min-width", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"min-width"},
  {"id"=>21, "title"=>"width", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"width"},
  {"id"=>22, "title"=>"font", "pvalues"=>"caption,icon,menu,message-box,small-caption,status-bar", "pvalues_desc"=>"Caption,Icon,Menu,Message-box,Small-caption,Status-bar", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"font"},
  {"id"=>23, "title"=>"font-family", "pvalues"=>"serif,sans-serif", "pvalues_desc"=>"Serif,Sans-serif", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"font-family"},
  {"id"=>24, "title"=>"font-size", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"%,em", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"font-size"},
  {"id"=>25, "title"=>"font-style", "pvalues"=>"normal,italic,oblique", "pvalues_desc"=>"Normal,Italic,Oblique", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"font-style"},
  {"id"=>26, "title"=>"font-variant", "pvalues"=>"normal,small-caps", "pvalues_desc"=>"Normal,Small-caps", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"font-variant"},
  {"id"=>27, "title"=>"font-weight", "pvalues"=>"normal,bold,bolder,lighter,100,200,300,400,500,600,700,800,900", "pvalues_desc"=>"Normal,Bold,Bolder,Lighter,100,200,300,400,500,600,700,800,900", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"font-weight"},
  {"id"=>28, "title"=>"list-style-image", "pvalues"=>"none,0i", "pvalues_desc"=>"None,0i", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"list-style-image"},
  {"id"=>29, "title"=>"list-style-position", "pvalues"=>"outside,inside", "pvalues_desc"=>"Outside,Inside", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"inherit", "css_name"=>"list-style-position"},
  {"id"=>30, "title"=>"list-style-type", "pvalues"=>"disc,none,circle,square,decimal,decimal-leading-zero,lower-roman,upper-roman,lower-alpha,upper-alpha,lower-greek,lower-latin,upper-latin,hebrew,armenian,georgian,cjk-ideographic,hiragana,katakana,hiragana-iroha,katakana-iroha", "pvalues_desc"=>"Disc,None,Circle,Square,Decimal,Decimal-leading-zero,Lower-roman,Upper-roman,Lower-alpha,Upper-alpha,Lower-greek,Lower-latin,Upper-latin,Hebrew,Armenian,Georgian,Cjk-ideographic,Hiragana,Katakana,Hiragana-iroha,Katakana-iroha", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"inherit", "css_name"=>"list-style-type"},
  {"id"=>31, "title"=>"margin", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"trbl", "css_name"=>"margin"},
  {"id"=>32, "title"=>"padding", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"trbl", "css_name"=>"padding"},
  {"id"=>33, "title"=>"bottom", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"", "css_name"=>"bottom"},
  {"id"=>34, "title"=>"clip", "pvalues"=>"auto,0r", "pvalues_desc"=>"Auto,0r", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"clip"},
  {"id"=>35, "title"=>"left", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"", "css_name"=>"left"},
  {"id"=>36, "title"=>"overflow", "pvalues"=>"visible,hidden,scroll,auto", "pvalues_desc"=>"Visible,Hidden,Scroll,Auto", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"overflow"},
  {"id"=>37, "title"=>"overflow-x", "pvalues"=>"visible,hidden,scroll,auto", "pvalues_desc"=>"Visible,Hidden,Scroll,Auto", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"overflow-x"},
  {"id"=>38, "title"=>"overflow-y", "pvalues"=>"visible,hidden,scroll,auto", "pvalues_desc"=>"Visible,Hidden,Scroll,Auto", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"overflow-y"},
  {"id"=>40, "title"=>"right", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"", "css_name"=>"right"},
  {"id"=>41, "title"=>"top", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"", "css_name"=>"top"},
  {"id"=>42, "title"=>"vertical-align", "pvalues"=>"baseline,sub,super,top,text-top,middle,bottom,text-bottom,l1", "pvalues_desc"=>"Baseline,Sub,Super,Top,Text-top,Middle,Bottom,Text-bottom,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"", "css_name"=>"vertical-align"},
  {"id"=>43, "title"=>"z-index", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"", "css_name"=>"z-index"},
  {"id"=>44, "title"=>"border-collapse", "pvalues"=>"collapse,separate", "pvalues_desc"=>"Collapse,Separate", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"inherit", "css_name"=>"border-collapse"},
  {"id"=>45, "title"=>"border-spacing", "pvalues"=>"l2", "pvalues_desc"=>"L2", "punits"=>"l", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"inherit", "css_name"=>"border-spacing"},
  {"id"=>46, "title"=>"caption-side", "pvalues"=>"top,bottom,left,right", "pvalues_desc"=>"Top,Bottom,Left,Right", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"caption-side"},
  {"id"=>47, "title"=>"empty-cells", "pvalues"=>"hide,show", "pvalues_desc"=>"Hide,Show", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"empty-cells"},
  {"id"=>48, "title"=>"table-layout", "pvalues"=>"auto,fixed", "pvalues_desc"=>"Auto,Fixed", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"table-layout"},
  {"id"=>49, "title"=>"color", "pvalues"=>"aqua,black,blue,fuchsia,gray,green,lime,maroon,navy,olive,purple,red,silver,teal,white,yellow,0c", "pvalues_desc"=>"Aqua,Black,Blue,Fuchsia,Gray,Green,Lime,Maroon,Navy,Olive,Purple,Red,Silver,Teal,White,Yellow,0c", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"inherit", "css_name"=>"color"},
  {"id"=>50, "title"=>"direction", "pvalues"=>"ltr,rtl", "pvalues_desc"=>"Ltr,Rtl", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"inherit", "css_name"=>"direction"},
  {"id"=>51, "title"=>"border-style", "pvalues"=>"none,hidden,double,solid,dashed,dotted,ridge,outset,groove,inset", "pvalues_desc"=>"None,Hidden,Double,Solid,Dashed,Dotted,Ridge,Outset,Groove,Inset", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"trbl", "css_name"=>"border-style"},
  {"id"=>52, "title"=>"letter-spacing", "pvalues"=>"normal,l1", "pvalues_desc"=>"Normal,L1", "punits"=>"l", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"letter-spacing"},
  {"id"=>53, "title"=>"text-align", "pvalues"=>"left,right,center,justify", "pvalues_desc"=>"Left,Right,Center,Justify", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"text-align"},
  {"id"=>54, "title"=>"text-decoration", "pvalues"=>"none,underline,overline,line-through,blink", "pvalues_desc"=>"None,Underline,Overline,Line-through,Blink", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"text-decoration"},
  {"id"=>55, "title"=>"text-indent", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"text-indent"},
  {"id"=>56, "title"=>"text-transform", "pvalues"=>"none,capitalize,uppercase,lowercase", "pvalues_desc"=>"None,Capitalize,Uppercase,Lowercase", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"text-transform"},
  {"id"=>57, "title"=>"white-space", "pvalues"=>"normal,pre,nowrap", "pvalues_desc"=>"Normal,Pre,Nowrap", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"white-space"},
  {"id"=>58, "title"=>"word-spacing", "pvalues"=>"normal,l1", "pvalues_desc"=>"Normal,L1", "punits"=>"l", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"inherit", "css_name"=>"word-spacing"},
  {"id"=>59, "title"=>"width", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"px", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"width"},
  {"id"=>60, "title"=>"href", "pvalues"=>"0u", "pvalues_desc"=>"Href", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"href"},
  {"id"=>61, "title"=>"src", "pvalues"=>"0i", "pvalues_desc"=>"Src", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"src"},
  {"id"=>62, "title"=>"alt", "pvalues"=>"0t", "pvalues_desc"=>"Alt", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"alt"},
  {"id"=>63, "title"=>"href", "pvalues"=>"0u", "pvalues_desc"=>"Href", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"href"},
  {"id"=>64, "title"=>"layout db", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"layout db"},
  {"id"=>65, "title"=>"layout string", "pvalues"=>"0t", "pvalues_desc"=>"0t", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"layout string"},
  {"id"=>66, "title"=>"layout themeimg", "pvalues"=>"0i", "pvalues_desc"=>"0i", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"layout themeimg"},
  {"id"=>67, "title"=>"layout bool", "pvalues"=>"0b", "pvalues_desc"=>"0b", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"layout bool"},
  {"id"=>68, "title"=>"layout int", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"layout int"},
  {"id"=>69, "title"=>"themenable var", "pvalues"=>"0t", "pvalues_desc"=>"0t", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"themenable var"},
  {"id"=>70, "title"=>"themenable db", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"themenable db"},
  {"id"=>71, "title"=>"themenable string", "pvalues"=>"0t", "pvalues_desc"=>"0t", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"themenable string"},
  {"id"=>72, "title"=>"themenable themeimg", "pvalues"=>"0i", "pvalues_desc"=>"0i", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"themenable themeimg"},
  {"id"=>73, "title"=>"themenable bool", "pvalues"=>"0b", "pvalues_desc"=>"0b", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"themenable bool"},
  {"id"=>74, "title"=>"themenable int", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"themenable int"},
  {"id"=>75, "title"=>"body-width-style", "pvalues"=>"0fluid,1fixedcentered,2fixed", "pvalues_desc"=>"0fluid,1fixedcentered,2fixed", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"body-width-style"},
  {"id"=>76, "title"=>"border-style", "pvalues"=>"none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset", "pvalues_desc"=>"None,Hidden,Dotted,Dashed,Solid,Double,Groove,Ridge,Inset,Outset", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"trbl", "css_name"=>"border-style"},
  {"id"=>77, "title"=>"border-width", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"trbl", "css_name"=>"border-width"},
  {"id"=>78, "title"=>"width", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"width"},
  {"id"=>79, "title"=>"height", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"height"},
  {"id"=>80, "title"=>"Heading", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"Heading"},
  {"id"=>81, "title"=>"Heading", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"Heading"},
  {"id"=>82, "title"=>"content var", "pvalues"=>"0t", "pvalues_desc"=>"0t", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"content var"},
  {"id"=>83, "title"=>"db", "pvalues"=>"0d", "pvalues_desc"=>"Please select a menu", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"db"},
  {"id"=>84, "title"=>"text", "pvalues"=>"0t", "pvalues_desc"=>"0t", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"text"},
  #content layout horizontally
  {"id"=>85, "title"=>"clear", "pvalues"=>"none,both", "pvalues_desc"=>"None,Both", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"clear"},
  {"id"=>86, "title"=>"horizontal", "pvalues"=>"0b", "pvalues_desc"=>"0b", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"clear"},
  {"id"=>87, "title"=>"content int", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"content int"},
  {"id"=>88, "title"=>"area var", "pvalues"=>"0t", "pvalues_desc"=>"0t", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"area var"},
  {"id"=>89, "title"=>"area db", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"area db"},
  {"id"=>90, "title"=>"area string", "pvalues"=>"0t", "pvalues_desc"=>"0t", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"area string"},
  {"id"=>91, "title"=>"area themeimg", "pvalues"=>"0i", "pvalues_desc"=>"0i", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"area themeimg"},
  {"id"=>92, "title"=>"fixed", "pvalues"=>"0b", "pvalues_desc"=>"0b", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"fixed"},
  {"id"=>93, "title"=>"area int", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"area int"},
  {"id"=>94, "title"=>"content sections", "pvalues"=>"0s", "pvalues_desc"=>"0s", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"content sections"},
  {"id"=>95, "title"=>"margin-top", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"margin-top"},
  {"id"=>96, "title"=>"margin-right", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"margin-right"},
  {"id"=>97, "title"=>"margin-bottom", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"margin-bottom"},
  {"id"=>98, "title"=>"margin-left", "pvalues"=>"auto,l1", "pvalues_desc"=>"Auto,L1", "punits"=>"l,%", "neg_ok"=>true, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"margin-left"},
  {"id"=>99, "title"=>"content sections", "pvalues"=>"1", "pvalues_desc"=>"1", "punits"=>"", "neg_ok"=>true, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"content sections"},
  {"id"=>100, "title"=>"width", "pvalues"=>"auto,100%,l1", "pvalues_desc"=>"Auto,100%,L1", "punits"=>"px", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"width"},
  {"id"=>101, "title"=>"float", "pvalues"=>"left,right,none", "pvalues_desc"=>"Left,Right,Center", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"float"},
  {"id"=>102, "title"=>"list_style", "pvalues"=>"basic,stardard_list,snapshot", "pvalues_desc"=>"Basic,Stardard list,Snapshot", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"list_style"},
  {"id"=>103, "title"=>"list_style", "pvalues"=>"list,ggrid,grid", "pvalues_desc"=>"List,Ggrid,Grid", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"list_style"},
  {"id"=>104, "title"=>"layout_style", "pvalues"=>"0,1", "pvalues_desc"=>"0,1", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"layout_style"},
  {"id"=>105, "title"=>"url", "pvalues"=>"0U", "pvalues_desc"=>"0u", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"url"},
  {"id"=>106, "title"=>"radio_hv", "pvalues"=>"0,1", "pvalues_desc"=>"0,1", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"radio_hv"},
  {"id"=>107, "title"=>"background-repeat", "pvalues"=>"no-repeat,repeat-x,repeat-y", "pvalues_desc"=>"No-repeat,Repeat-x,Repeat-y", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"background-repeat"},
  {"id"=>108, "title"=>"padding-left", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"padding-left"},
  {"id"=>109, "title"=>"padding-right", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l,%", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"padding-right"},
  {"id"=>110, "title"=>"padding", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"trbl", "css_name"=>"padding"},
  {"id"=>111, "title"=>"margin", "pvalues"=>"l1", "pvalues_desc"=>"L1", "punits"=>"l", "neg_ok"=>true, "default_value"=>0, "pvspecial"=>"trbl", "css_name"=>"margin"},
  {"id"=>112, "title"=>"background-image", "pvalues"=>"0i", "pvalues_desc"=>"0i", "punits"=>"", "neg_ok"=>false, "default_value"=>0, "pvspecial"=>"", "css_name"=>"background-image"},
  {"id"=>113, "title"=>"background-repeat", "pvalues"=>"repeat-y,no-repeat", "pvalues_desc"=>"Repeat-y,No-repeat", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"background-repeat"},
  {"id"=>114, "title"=>"background-repeat", "pvalues"=>"repeat-x,no-repeat", "pvalues_desc"=>"Repeat-x,No-repeat", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"background-repeat"},
  {"id"=>115, "title"=>"composite", "pvalues"=>"", "pvalues_desc"=>"", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"composite"},
  {"id"=>116, "title"=>"sitemap_view_style", "pvalues"=>"1,0", "pvalues_desc"=>"1,0", "punits"=>"", "neg_ok"=>false, "default_value"=>-1, "pvspecial"=>"", "css_name"=>"sitemap_view_style"},
  {"id"=>117, "title"=>"composite", "pvalues"=>"1809,1810,1811,1812,1813", "pvalues_desc"=>"1809,1810,1811,1812,1813", "punits"=>"", "neg_ok"=>false, "default_value"=>1, "pvspecial"=>"", "css_name"=>"composite"}]

Spree::HtmlAttribute.delete_all              
for ha in objs
  obj = Spree::HtmlAttribute.new
  obj.assign_attributes( ha,  :without_protection => true)
  obj.save
end
                
