ror_baseball_size:
  product: ror_baseball_jersey
  option_type: size
  position: 1
ror_baseball_color:
  product: ror_baseball_jersey
  option_type: color
  position: 2
spree_baseball_size:
  product: spree_baseball_jersey
  option_type: size
  position: 3
spree_baseball_color:
  product: spree_baseball_jersey
  option_type: color
  position: 4
