source 'http://rubygems.org'
#source "https://rails-assets.org"



group :test,:development do
  gem 'ruby-graphviz' #print checkout flow
  gem 'simplecov' #rspec using it.
  #using backend required
  gem "mysql2"
  gem 'spree', :github => "spree/spree", :branch => "2-4-stable"
  gem 'spree_auth_devise', :github => "spree/spree_auth_devise", :branch => "2-4-stable"
end

#group :test do
#  gem 'ffaker'
#end

gem "acts_as_list"
gem "acts_as_tree"
gem "awesome_nested_set"

# spree already contain
#gem 'jquery-rails'
gem 'useragent'
gem "friendly_id"

group :assets do
  gem 'sass'
  gem 'coffee-rails'
end
#gem 'ssl_requirement'

#gem 'bootstrap-sass', '~> 3.3.1'
#gem 'sass-rails', '>= 3.2'

gemspec
