source 'http://rubygems.org'
source "https://rails-assets.org"


gem 'spree', '~>2.4'

group :test,:development do
  gem 'ruby-graphviz' #print checkout flow
  gem 'simplecov' #rspec using it.
  #using backend required
  gem "mysql2"
end

#group :test do
#  gem 'ffaker'
#end

gem "acts_as_list"
gem "acts_as_tree"
gem "awesome_nested_set"

# spree already contain
#gem 'jquery-rails'
#gem 'jquery-ui-rails'
gem "friendly_id"

group :assets do
  gem 'sass'
  gem 'coffee-rails'
end
#gem 'ssl_requirement'
gemspec
