#source 'http://gems.ruby-china.org'
source 'https://rubygems.org/'

eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))


group :test,:development do
  #gem 'ruby-graphviz' #print checkout flow
  #gem 'simplecov' #rspec using it.
  #using backend required
  gem 'sass-rails', '~> 5.0.0'
  gem "mysql2"
end

group :test do
  gem 'ffaker'
  gem 'shoulda-matchers', '~> 3.1'
end

gem "acts_as_list"
gem "acts_as_tree"
gem "awesome_nested_set"
gem 'acts_as_commentable'

# spree already contain
#gem 'jquery-rails'
gem 'useragent'
gem "friendly_id"

gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'sitemap_generator'

#gem 'bootstrap-sass'
#gem 'font-awesome-rails'
# support multiple theme by file
#gem 'themes_on_rails',  github: "spree/spree_editor", branch: "master"

gemspec
