source 'https://ruby.taobao.org'
#source 'http://rubygems.org'
#do not inlucde spree_devise_auth, or spec has to skip authorization
#eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))

gemspec
