source 'http://ruby.taobao.org'
#source 'http://rubygems.org'


group :development,:test do
  gem 'mysql2'
  #gem 'mail_view'
  # Provides basic authentication functionality for testing parts of your engine
  gem 'spree', '~>2.4' # required to create dummy
  #test require it. site create user
  #gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
end

gemspec
